/* Generated by BuildNumber V2.0 */ 

#ifndef BUILD_NUMBER_H
#define BUILD_NUMBER_H

#define BUILDNUMBER 4
#define BUILDNUMBER_STR "004"
#define VER_MAJOR 0
#define VER_MINOR 0
#define VERSION_STR "0.00.004"
#define BUILDDATE_STR "2023-04-13 11:39:01"

#endif


| Error						   | No.|
|:-----------------------------|:--:|
| Maximum build number reached | -4 |
|------------------------------+----+
| Error while parsing		   | -3 |
|------------------------------+----+
| Could not create file 	   | -1 |
|------------------------------+----+
| Normal exit  	         	   |  0 |
