/* Generated by BuildNumber V2.2 */ 

#ifndef BUILD_NUMBER_H
#define BUILD_NUMBER_H

#define BUILDNUMBER 11						// Build number as Integer
#define BUILDNUMBER_STR "11"				// Build number as String
#define VER_MAJOR 1							// Major version number as Integer
#define VER_MINOR 34							// Minor version number as Integer
#define MAJORMINOR_STR  "0134"				// MajorMinor number as String
#define MAJORMINOR 134							// MajorMinor version number as Integer
#define VERSION_STR "1.34.02"				// Version number as String
#define BUILDDATE_STR "2024-11-20 12:47:26"	// Creation Date as String

#endif
