/* Generated by BuildNumber V2.1 */ 

#ifndef BUILD_NUMBER_H
#define BUILD_NUMBER_H

#define BUILDNUMBER 3						// Build number as Integer
#define BUILDNUMBER_STR "03"				// Build number as String
#define VER_MAJOR 0							// Major version number as Integer
#define VER_MINOR 0							// Minor version number as Integer
#define VERSION_STR "0.00.03"				// Version number as String
#define BUILDDATE_STR "2023-11-24 09:57:02"	// Creation Date as String

#endif
